name: uz_phone_validator
description: O'zbekcha telefon raqamnlarni tekshirish packagesi.
version: 2.0.0
homepage: https://github.com/islombek885/uz_phone_validator

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: